[target.'cfg(debug_assertions)']
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
ar = "aarch64-linux-gnu-gcc"
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-gnueabihf]
ar = "arm-linux-gnueabihf-gcc"
linker = "arm-linux-gnueabihf-gcc"

[target.'cfg(unix)']
runner = "sudo -E"
rustflags = ["-C", "link-args=-rdynamic"]

[net]
git-fetch-with-cli = true
