name: Publish
on: [push, pull_request]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ali ossutil
        uses: yizhoumo/setup-ossutil@v2
        with:
          endpoint: ${{ secrets.AWS_ENDPOINT }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Publish
        env:
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash ./ci.sh
