name: Publish
on: [push, pull_request]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: lebai/plugin:latest
          build-args: |
            AWS_ENDPOINT=${{ secrets.AWS_ENDPOINT }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
