name: Publish
on: [push, pull_request]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Publish
        uses: mosteo-actions/docker-run@v2
        with:
          image: registry.cn-shanghai.aliyuncs.com/lebai/util:14.04
          host-dir: "."
          guest-dir: /app
          params: "-e AWS_ENDPOINT=${{ secrets.AWS_ENDPOINT }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          command: |
            bash ./ci.sh
